# Generated by Django 2.1.7 on 2019-06-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_auto_20190609_0922'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musiclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account')),
                ('music', models.ManyToManyField(to='music.Music')),
            ],
        ),
    ]
