# Generated by Django 2.1.7 on 2019-06-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musiclist',
            old_name='music',
            new_name='musics',
        ),
    ]
