# Generated by Django 2.1.7 on 2019-06-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='authorities',
            field=models.ManyToManyField(to='authority.Authority'),
        ),
    ]
